general.import = [
  "~/.config/alacritty/nord.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 1.0
blur = true

  [window.dimensions]
  columns = 150
  lines = 45

  [window.padding]
  x = 20
  y = 20

[font]
size = 14.0
builtin_box_drawing = true

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono NFM"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono NFM"
  style = "Bold Italic"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "1", mods = "Control" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
regex = '[^ ]+(:?\s*)$'
command = { program = "/opt/homebrew/bin/tmux", args = ["split-window", "-h", "-c", "#{pane_current_path}", "sh", "-c", "hx \"$0\""] }
binding = { key = "2", mods = "Control" }
